### ISSUE TITLE
Whitelist certain HTML tags

### ISSUE THREAD

**Issue by imaustink** [bit-docs/bit-docs-generate-searchmap#5]
https://github.com/bit-docs/bit-docs-generate-searchmap/pull/4#pullrequestreview-40634649

**Comment by chasenlehara** [comment]
I think this was implemented: https://github.com/bit-docs/bit-docs-generate-searchmap/blob/0757d196cc6de96274541e1f93cd6c601f96ae1a/generators/search-map.js#L42
