### ISSUE TITLE
Remove url property

### ISSUE THREAD

**Issue by chasenlehara** [bit-docs/bit-docs-generate-searchmap#8]
The `url` property is included in the search map, but I don’t think it’s necessary for getting good search results. I think it’s worth experimenting in [bit-docs-html-canjs](https://github.com/canjs/bit-docs-html-canjs) whether it’s actually needed; if it’s not, then that would be a nice size savings.

**Comment by imaustink** [comment]
@chasenlehara without a `url` field, the client will need to have access to the `docMap.json` or another map must be generated to map `name` to `url` so that we can extrapolate the URL on the client.

**Comment by chasenlehara** [comment]
Oh duh, obviously we need it for them to click on the result. 🙈
